name: campus_connect
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  chat_bubbles: ^1.2.0
  cloud_firestore: ^3.1.10
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  fluentui_system_icons: ^1.1.161
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.3
  salomon_bottom_bar: ^3.2.0
  shared_preferences: ^2.0.13
  supabase: ^0.2.14
  supabase_flutter: ^0.2.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
